export const CreateProductBodySchema = {
	$id: "CreateProductBody",
	type: "object",
	properties: {
		stock: { type: "number" },
		name: {
			type: "string",
		},
		price: { type: "number" },
		expireDate: { type: "string" },
		category: { type: "string" },
		image: { type: "string" },
		region: { type: "string" },
		isPersonalized: { type: "boolean" },
		flavor: { type: "string" },
		capes: { type: "number" },
		size: { type: "string" },
		decoration: { type: "string" },
		filling: { type: "string" },
		reference: { type: "string" },
		orderDetails: { type: "string" },
	},
	required: [
		"stock",
		"name",
		"expireDate",
		"category",
		"region",
		"price",
		"isPersonalized",
	],
};
